### ISSUE TITLE
Giscus pane not utilizing available width 

### ISSUE THREAD

**Issue by bravo-kernel** [timlrx/pliny#100]
**Describe the bug**
Currently, a fresh generated Pliny blog with Giscus enabled:

- Produces a Giscus comments pane that is not using 100% available width
- Which makes it appear as only 25% of available space is used 
- As can be seen (and described) in [this Giscus issue. ](https://github.com/giscus/giscus/issues/76)

**To Reproduce**
1. Generate a fresh Pliny blog
2. Enable Giscus
3. Check width of the comments pane

**Expected behavior**
Giscus comments pane should utilize 100% available width

## Suggested Fix
The fix suggested in above Giscus thread is simple:

```
.giscus, .giscus-frame {
    width: 100%;
}
```

Solved for my blog by adding a new css file for overrides [as can be seen here](https://github.com/bravo-kernel/bravo-kernel.com/pull/168/files).

## Question

Are you open to a PR and if so, do you prefer a different implementation?

**Comment by jaybxyz** [comment]
@bravo-kernel Thanks for the workaround. This happens to me as well and I have been looking for a solution.

**Comment by timlrx** [comment]
@bravo-kernel, thanks for proposing fix a while back! I decided to update the component and use the official react component in the new beta version.
