### ISSUE TITLE
Replace pliny sitemap with next-sitemap

### ISSUE THREAD

**Issue by bravo-kernel** [timlrx/pliny#101]
I suggest replacing custom pliny sitemap-code with [iamvishnusankar/next-sitemap](https://github.com/iamvishnusankar/next-sitemap) for the following reasons:

- Less code to maintain in pliny
- Complex sitemap-specific code outsourced to the responsible library
- Solves some current issues with pliny sitemap code (e.g. incidental broken tags and broken page URLs)
- Prepares for i18n (looks for `alternateRefs` on [next-sitemap configuration options](https://github.com/iamvishnusankar/next-sitemap)
- Also:
  - handles proper `robots.txt` as requested in https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/613
  - handles `lastmod` as requested in https://github.com/timlrx/tailwind-nextjs-starter-blog/issues/433

The suggested code changes can be seen in this PR https://github.com/bravo-kernel/bravo-kernel.com/pull/169.

Are you ok with a PR for Pliny?

**Comment by timlrx** [comment]
I would be migrating to app dir with v2 and use the in-built metadata support. Will see if it an additional package still makes sense after the migration.

**Comment by timlrx** [comment]
I have opted to use Next 13 metadata support which handles robots.txt as well.
