### ISSUE TITLE
The plugin system prevents static NextJS builds

### ISSUE THREAD

**Issue by Mike-Dax** [timlrx/pliny#102]
**Describe the bug**
With a static NextJS build, using `output: 'export',`, the `redirects` configuration causes a build error:

```
Error: Specified "redirects" cannot but used with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export
```

**To Reproduce**
- Download and install the starter blog. Upgrade to NextJS `13.2.4`
- Set `output: 'export'` 
- Try to build.

**Expected behavior**
I'd expect to be able to build a static site, even if I manually need to run some commands to have the 'watch mode' work with contentlayer

**Comment by timlrx** [comment]
Sorry for the late reply here, but for future reference it depends on which particular functionality of the library is used. Aside from the newsletter API route, the other components do not require a backend server and will work in a static build. For an end to end demo of all the functionalities, you can check out my [template blog and the instructions for a static build](https://github.com/timlrx/tailwind-nextjs-starter-blog?tab=readme-ov-file#static-hosting-services-github-pages--s3--firebase-etc).
