### ISSUE TITLE
This project seems to be inactive..

### ISSUE THREAD

**Issue by wzono** [timlrx/pliny#104]
Many bugs are in hurry to be fixed, but no action for them..
@timlrx

**Comment by timlrx** [comment]
Indeed, sorry about the inactivity. Too many breaking changes with next 13 and I am probably looking at a more streamline approach to make the components available across projects while not having to deal with all the additional scaffolding, transpiling, change management add-ons.

**Comment by timlrx** [comment]
I have restructured the project to only maintain the components and updated them to be compatible with next 13 app dir. The blog template is back over at https://github.com/timlrx/tailwind-nextjs-starter-blog/pull/658
