### ISSUE TITLE
Wrong link for umami analytics

### ISSUE THREAD

**Issue by harrison-broadbent** [timlrx/pliny#105]
Hey, I was trying to use Umami analytics in a tailwind-next-starter project but I keep getting errors about it being the wrong script URL. I think the problem is here — 

https://github.com/timlrx/pliny/blob/1e82c4e45fb2ea8533aeb6c265822acf312e7067/packages/pliny/src/analytics/Umami.tsx#L14

I believe the URL should be — https://analytics.umami.is (worth double checking though). 
It would also be cool if the analytics scripts were automatically proxied to improve tracking (I do this manually currently). 

Hope this helps, thanks!

**Comment by timlrx** [comment]
Thanks! Realized that umami launched its cloud service. Have updated `src` to point to `https://analytics.umami.is/script.js`. Have also exposed `src` or `host` in the components so they can be more easily proxied.

**Comment by harrison-broadbent** [comment]
thanks!
