### ISSUE TITLE
support generate full content RSS feeds and support config output xml name

### ISSUE THREAD

**Issue by ttys3** [timlrx/pliny#107]
**Is your feature request related to a problem? Please describe.**

I come from other site generator, which I configured to generate full content RSS feeds.

after migrated to pliny, I see it only generate `summary` based RSS feeds.

and the output xml name is fixed to `feed.xml`, which I used to use `atom.xml` in prev.

so it is good to have this filename configureable

**Describe the solution you'd like**

have config option to allow choose between **full content RSS feeds** and **summary only RSS feeds**

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by timlrx** [comment]
As you might have noticed, I now inline the logic of the RSS feed to the blog template. Hopefully this makes it easy to customize it to your liking. I have also parameterized the rss feed name. If there are further changes that you would like to make, feel free to open a PR, thanks!
