### ISSUE TITLE
Minor change requests to make search more generalizable

### ISSUE THREAD

**Issue by Mochael** [timlrx/pliny#130]
**Is your feature request related to a problem? Please describe.**
Love what you've built! There are 2 minor issues I have with search functionality right now that can be easily changed, depending on what you think. [Both changes can be made in this file](https://github.com/timlrx/pliny/blob/c103d9ed340458b81b7ee74d54b0f42b81e25dc0/packages/pliny/src/search/KBar.tsx#L48) 
1. I don't want the home page to be searchable. If I wanted home page to be searchable I could just index it along with the other posts.
2. It would be awesome if you could instead make section titles in the search modal be defined in the index, instead of being defined manually in the file I mentioned. Right now there's only "Home" and "Content". What if I have 4 different types of things that I define in my JSON index, and I want these split up in different sections?

**Comment by timlrx** [comment]
Thanks, I am open to making it more customizable.

1. You can pass a `defaultActions` to the `kbarConfig` prop in `KBarSearchProvider`. I believe you should be able to pass in an empty array to start on a blank slate.
2. Not sure if I understand what you mean, but you could consider defining the different sections and passing it to the `defaultActions` prop as mentioned above. Modifying the content to be loaded later is a little difficult as it assumes you have a `searchDocumentsPath` and imposes a fix `mapPosts` function to transform it. Would you like to pass your own `mapPosts` function to tranform the documents from `searchDocumentsPath`?

**Comment by Mochael** [comment]
Thanks for clarifying! Using `defaultActions` pretty much solved what I needed. I do think a more first class approach though would be the ability to specify your own `mapPosts` functions to transform different types of documents
