### ISSUE TITLE
remarkImgToJsx removed text around images

### ISSUE THREAD

**Issue by L4ys** [timlrx/pliny#135]
**Describe the bug**
When a paragraph includes both text and an image, the text within the paragraph is removed by `remarkImgToJsx` during the transformation.

**To Reproduce**
1. Create a blog post file with the following markdown content:

```md
This is some text.
![Image](/path/to/image.jpg)
This is some more text.
```

This will gererate following HTML without `remarkImgToJsx`:
```html
<p>
  This is some text.
  <img alt="Image" src="/path/to/image.jpg">
  This is some more text.
</p>
```

2. In the output HTML, only the image remains, and the text in the paragraph is removed:
```html
<div>
  <img ...>
</div>
```

**Expected behavior**
The transformed output should include all the content in the paragraph, both text and image:

```html
<p>This is some text.</p>
<div>
  <img ...>
</div>
</p>This is some more text.</p>
```
or maybe:
```html
<p>
  This is some text.
  <img ...>
  This is some more text
</p>
```

**Additional context**
This is because `remarkImgToJsx` directly replaces the entire `<p>` node:

https://github.com/timlrx/pliny/blob/99350ca2d176a3d29d1a7a632bb7def99f5e8692/packages/pliny/src/mdx-plugins/remark-img-to-jsx.ts#L43

I attempted to patch this behavior by modifying the code like so:
```ts
// Change node type from p to div to avoid nesting error
node.type = 'div';
// Commented out the line that overwrites node children
// node.children = [imageNode];
```
I'm not entirely sure if this would introduce other issues, so it would be great if you could take a look at it.

Would there be any unintended consequences if we directly replace the img node?

**Comment by timlrx** [comment]
Sorry for the late reply. Commenting out the line would not fix it - it will just use the default image which sort of defeats the purpose of this plugin. I have fixed it by specifically targeting the image node and replacing it.
