### ISSUE TITLE
mdx image support avif

### ISSUE THREAD

**Issue by ttys3** [timlrx/pliny#140]
**Is your feature request related to a problem? Please describe.**

my build failed after I add an avif image (like `xxxxx.avif` file) to mdx

```shell
npm build
2:22:05 AM: > tailwind-nextjs-starter-blog@1.5.6 build /opt/build/repo
2:22:05 AM: > cross-env INIT_CWD=$PWD next build && cross-env NODE_OPTIONS="--experimental-json-modules" node ./scripts/postbuild.mjs
2:22:06 AM: - info Creating an optimized production build...
2:22:16 AM: ✘ [ERROR] TypeError: unsupported file type: undefined (file: /opt/build/repo/public/static/images/blog/2023-09-28_02-19-flameshot-config-save-path-and-save-extension-9ac8df864e.avif)
2:22:16 AM:     at lookup (/opt/build/repo/node_modules/.pnpm/image-size@1.0.0/node_modules/image-size/dist/index.js:51:11)
2:22:16 AM:     at imageSize (/opt/build/repo/node_modules/.pnpm/image-size@1.0.0/node_modules/image-size/dist/index.js:118:16)
2:22:16 AM:     at file:///opt/build/repo/node_modules/.pnpm/pliny@0.1.0-beta.10_@algolia+client-search@4.18.0_@types+react@18.2.14_esbuild@0.18.11_next@1_5de4fbg5pxn3x3gr2p4emqpuki/node_modules/pliny/chunk-PNQ6HFY5.js:15:30
```

**Describe the solution you'd like**

use https://www.npmjs.com/package/probe-image-size instead since it support avif.

image-size is not likely to add avif support in a rather short time. since this issue has been 3 years and no impl:

https://github.com/image-size/image-size/issues/348

**Describe alternatives you've considered**

wait https://www.npmjs.com/package/image-size or we fork https://www.npmjs.com/package/image-size and add avif support

**Additional context**

avif almost suported by all popular modern web browsers

https://caniuse.com/avif

**Comment by timlrx** [comment]
Thanks, I am good with switching out `image-size` with `probe-image-size`. Let me know if you want to work on that change or I will try to push an update in the upcoming week.

**Comment by ttys3** [comment]
PR opened, I tested this on my production site, it works fine
