### ISSUE TITLE
Add translation to newsletterform component

### ISSUE THREAD

**Issue by nextrie** [timlrx/pliny#154]
**Is your feature request related to a problem? Please describe.**
I am french and would like to display the components in french instead of english

**Describe the solution you'd like**
Add translation props so that I can make the form french without having to fork the project

![image](https://github.com/timlrx/pliny/assets/40547005/ee4db637-9534-4187-92f3-48e985c83eee)

**Comment by timlrx** [comment]
Hi @nextrie, I think the easiest way would be to just create a copy of the component from https://github.com/timlrx/pliny/blob/main/packages/pliny/src/ui/NewsletterForm.tsx and edit the text directly. I could create multiple props for the different fields but it seems overcomplicating it for a simple ui component.

**Comment by nextrie** [comment]
Makes sense, thank you for your help !
