### ISSUE TITLE
 WARN  Issues with peer dependencies found

### ISSUE THREAD

**Issue by johanguse** [timlrx/pliny#161]
I think it's time to update some depends, the contentlayer is not  getting new updates, so maybe you should move to another solution https://github.com/contentlayerdev/contentlayer/issues/429

![image](https://github.com/timlrx/pliny/assets/6184866/7d8dc0b9-f9e8-4edd-97de-de0dbed1abb0)

**Comment by timlrx** [comment]
Used the new contentlayer fork - `contentlayer2` and updated dependencies. Published as `0.2.0`.
