### ISSUE TITLE
Can SearchProvider support searching for article content rather than just titles

### ISSUE THREAD

**Issue by jiangxiaoyu66** [timlrx/pliny#167]

**Comment by timlrx** [comment]
Hmm it should be possible - have to check on the performance . My concern is that it might take to long to load an search the index.

**Comment by timlrx** [comment]
Take a look at https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/main/faq/customize-kbar-search.md for a more detailed write-up on the modifications required.
