### ISSUE TITLE
Add template and starter for docs

### ISSUE THREAD

**Issue by timlrx** [timlrx/pliny#24]
# To do:

- [ ] Standardized markdown frontmatter format. Ideally the format should be consistent across various static docs generators, making it easy to port over.
- [ ] Create design for docs based on tailwind css
- [ ] Create starter-docs
- [ ] Create recipe to import docs theme
- [ ] Create recipe to bootstrap starter docs

## References:
- [Docusaurus frontmatter fields](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#markdown-front-matter)
- [Vuepress frontmatter fields](https://vuepress.vuejs.org/guide/frontmatter.html#predefined-variables)
- [Contentlayer's doc and settings](https://github.com/contentlayerdev/website)
- [Mkdocs](https://www.mkdocs.org/user-guide/writing-your-docs/)

**Comment by timlrx** [comment]
React beta docs might be another good source of inspiration - https://github.com/reactjs/reactjs.org/tree/fx/beta

**Comment by GeauxWeisbeck4** [comment]
> @GeauxWeisbeck4 I have merged in the search feature branch as well as a bunch of bug fixes so it should be a relatively clean state to work on, though let me know if you find anything amiss.

Ok awesome - I love all of those resources. I will work off of the `/search` branch then.
