### ISSUE TITLE
Add second blog theme

### ISSUE THREAD

**Issue by timlrx** [timlrx/pliny#25]
Variety is good and we can get more people to try out the recipes.

Something like [distill](https://distill.pub/2020/understanding-rl-vision/) would be nice or [one with side footnotes](https://www.gwern.net/Sidenotes).

**Comment by saqibameen** [comment]
Hey, I am not sure what the time commitment looks like for this project, but I would be happy to contribute.

**Comment by timlrx** [comment]
Hey, there's no real commitment, but if you create a new blog template that is relatively distinct from the current one, feel free to make a PR and submit it as a recipe for others to adopt. Steps:

1) Clone the repository and install all dependencies:
```bash
yarn
yarn build
```
1) Create a new folder: `pliny/recipes/blog-[template name]` and copy the code in [`pliny/recipes/blog-classic`](https://github.com/timlrx/pliny/tree/main/recipes/blog-classic)
2) Modify the description in the [recipe builder](https://github.com/timlrx/pliny/blob/main/recipes/blog-classic/index.ts#L6)
3) Replace `PostLayout.tsx`, `PostSimple.tsx`, `ListLayout.tsx` with your template. Note, template should be a standalone file as all of it will be copied over to the layout folder. It can assume that other components already exist in the `starter-blog` folder. That's the purpose of the tsconfig.json file - to simulate that it is in the starter-blog.
4) Try it out locally. From the start-blog folder run: `node ../packages/cli/bin/run install ../recipes/blog-[template name]`.  Try adding/changing one of the mdx blog to include a layout field in the frontmatter with your template name. Run `yarn dev:starter` which should launch the starter blog, and verify that it displays as intended.
5) If everything is fine, submit the recipe as a PR 🎉 

There's no docs for now, but for more information check out Blitzjs's [writing a recipe](https://blitzjs.com/docs/writing-recipes) and [templating language](https://blitzjs.com/docs/templates), since the recipe builder and templating solution is very much adapted from Blitzjs with some additional utility functions for contentlayer and fixes the support copying recursive directories. If you run into any issues, let me know and I would help you along the way especially if you are the first contributor =)

**Comment by GeauxWeisbeck4** [comment]
Is this still open or is there room for another template? This would be a fun contribution.

**Comment by timlrx** [comment]
Yup, most certainly!

**Comment by mandeepsng** [comment]
I am happy to contribution @timlrx

**Comment by timlrx** [comment]
@mandeepsng happy to accept a contribution as well

**Comment by npenza** [comment]
Happy to work on this 😃 @timlrx
