### ISSUE TITLE
pliny install on mac with any command segfaults

### ISSUE THREAD

**Issue by rufuspollock** [timlrx/pliny#73]
When running `pliny install` on mac results in segfault e.g.

```
zsh: segmentation fault  pliny install add-classic
```

There is no additional output

**To Reproduce**

1. Install pliny as per instructions: `npm i -g @pliny/cli `(`pliny --version` outputs '0.0.5')
2. Try to use `pliny install` e.g. `pliny install add-blog ContentDir=content ContentName=Blog`
4. See error: `zsh: segmentation fault  pliny install add-blog ContentDir=content ContentName=Blog`

Note that `pliny install` works and puts up a prompt. if you select any option from list it seg faults.

**Expected behavior**

Command to work and add the template.

**Screenshots**

**System Info (if dev / build issue):**

Output of version command

@pliny/cli/0.0.5 darwin-x64 node-v16.5.0

**Comment by timlrx** [comment]
Fixed in https://github.com/timlrx/pliny/pull/74 and published as `0.0.6`
