### ISSUE TITLE
Giscus not loading due to Content Security Policy

### ISSUE THREAD

**Issue by flov** [timlrx/pliny#82]
Hi,

I'm trying to get Giscus working in my blog https://flow-wizard.xyz but I'm struggling with the giscus implementation.
It is said in the readme that the content security policy needs to be changed. But it doesn't say **how** it should be changed.
I've added the giscus env variables in `.env` but when I render the page and click on Load Comments, it outputs this in the console:

```
Refused to frame 'https://giscus.app/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".
Failed to load resource: the server responded with a status of 404 ()
```
I've tried adding `frame-src 'self' giscus.app https://giscus.app;` inside next.config.js but the same error stays

When I render the giscus script that was given to me by giscus.app (`<Script ... />`) inside the layout file it actually loads, but only on a refresh.

**Comment by daaain** [comment]
Have you added `giscus.app` both to `script-src` and `frame-src`?

See here: https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/next.config.js#L6-L15

**Comment by spencerwooo** [comment]
@flov You may need to explicitly set `lang: 'en'` inside `giscusConfig`:

```diff js
giscusConfig: {
  // ...
  // If the theme option above is set to 'custom`
  // please provide a link below to your custom theme css file.
  // example: https://giscus.app/themes/custom_example.css
  themeURL: '',
+ // This corresponds to the `data-lang="en"` in giscus's configurations
+ lang: 'en',
},
```
