### ISSUE TITLE
Conditional pages

### ISSUE THREAD

**Issue by bravo-kernel** [timlrx/pliny#86]
It would be nice if pages could be enabled/disabled using [siteMetaData](https://github.com/timlrx/pliny/blob/main/starter-blog/data/siteMetadata.js). E.g.

- `/about` => both navbar and direct link to the page
- `/projects` => both navbar and direct link to the page

**Describe alternatives you've considered**
The current situation: manually deleting `/pages/about.tsx` and `/pages/projects.tsx`, then stripping `headerNavLinks.ts`.

**Comment by bravo-kernel** [comment]
ohw https://github.com/timlrx/pliny/blob/c900466ff881147dedf19e0e2d920be426b027e3/starter-blog/data/siteMetadata.js

**Comment by timlrx** [comment]
Probably won't implement it, feels too much work for a few deletes

**Comment by bravo-kernel** [comment]
Fair enough 👍
