### ISSUE TITLE
Can you please add to Readme file how to use this

### ISSUE THREAD

**Issue by mandeepsng** [timlrx/pliny#98]
**Describe the bug**
I install all using readme file instruction but now when I am starting 
`yarn dev`
its not working

**Screenshots**

<img width="1440" alt="Screenshot 2023-02-08 at 5 14 23 PM" src="https://user-images.githubusercontent.com/80085652/217520859-af821a6d-fac8-4dc3-8599-c400482e6b1c.png">

correct me where I am wrong.
Thank you

**Comment by timlrx** [comment]
Can you please read the [readme](https://github.com/timlrx/pliny#installation) first? There's no need to clone the entire repo. Just run `npm i -g @pliny/cli` to install the cli followed by `pliny new --template=starter-blog my-blog` to create a new starter blog project called "my-blog"

**Comment by mandeepsng** [comment]
@timlrx 
now its working 
thank you
